export const TRANSACTION_PHASES = [
  { id: "all", label: "All Services" },
  { id: "pre_offer", label: "Pre-Offer" },
  { id: "inspection", label: "Inspection" },
  { id: "appraisal", label: "Appraisal" },
  { id: "mortgage", label: "Mortgage" },
  { id: "closing", label: "Closing" },
  { id: "post_close", label: "Post-Close" },
];

export const CATEGORIES = [
  { id: "mortgage", label: "Mortgage Services", icon: "🏦" },
  { id: "real_estate", label: "Real Estate Services", icon: "🏡" },
  { id: "inspection", label: "Inspection Services", icon: "🔬" },
  { id: "appraisal", label: "Appraisal Services", icon: "📊" },
  { id: "legal", label: "Legal Services", icon: "⚖️" },
  { id: "insurance", label: "Insurance Services", icon: "🛡️" },
  { id: "moving", label: "Moving Services", icon: "📦" },
  { id: "cleaning", label: "Cleaning Services", icon: "✨" },
  { id: "post_close", label: "Post-Closing Services", icon: "🔑" },
];

export const SERVICES = [
  // ── APPRAISAL ──
  {
    id: "appraisal_standard",
    category: "appraisal",
    phases: ["appraisal"],
    name: "Standard Appraisal Coordination",
    description: "Full coordination with a licensed CA-certified appraiser — scheduling, access management, and report delivery.",
    tokens: 500,
    pct: "~3.5%",
    deliveryTime: "5–7 business days",
    badge: "Most Common",
    badgeColor: "bg-blue-500/20 text-blue-300 border-blue-500/30",
    certifications: ["CA Certified Appraiser", "USPAP Compliant"],
    experience: "10+ yrs avg",
    rating: 4.8,
    reviews: 142,
    aiTip: null,
  },
  {
    id: "appraisal_rush",
    category: "appraisal",
    phases: ["appraisal"],
    name: "Rush Appraisal Coordination",
    description: "Expedited appraisal scheduling for time-sensitive transactions. Priority queue access.",
    tokens: 750,
    pct: "~5%",
    deliveryTime: "2–3 business days",
    badge: "Rush",
    badgeColor: "bg-amber-500/20 text-amber-300 border-amber-500/30",
    certifications: ["CA Certified Appraiser", "USPAP Compliant"],
    experience: "12+ yrs avg",
    rating: 4.7,
    reviews: 67,
    aiTip: null,
  },
  {
    id: "appraisal_complex",
    category: "appraisal",
    phases: ["appraisal"],
    name: "Complex Property Appraisal Review",
    description: "For properties with mixed use, ADUs, unusual lot conditions, or limited comps requiring specialist review.",
    tokens: 850,
    pct: "~6%",
    deliveryTime: "7–10 business days",
    badge: null,
    badgeColor: null,
    certifications: ["CA Certified Appraiser", "Complex Property Specialist"],
    experience: "15+ yrs avg",
    rating: 4.9,
    reviews: 38,
    aiTip: null,
  },
  {
    id: "appraisal_luxury",
    category: "appraisal",
    phases: ["appraisal"],
    name: "Luxury / Unique Property Appraisal",
    description: "Specialist appraisers for high-value, architecturally significant, or estate properties.",
    tokens: 1000,
    pct: "~7%",
    deliveryTime: "7–14 business days",
    badge: "Premium",
    badgeColor: "bg-amber-500/20 text-amber-300 border-amber-500/30",
    certifications: ["CA Certified Appraiser", "Luxury Market Specialist"],
    experience: "18+ yrs avg",
    rating: 4.9,
    reviews: 24,
    aiTip: null,
  },
  {
    id: "appraisal_rov",
    category: "appraisal",
    phases: ["appraisal"],
    name: "Reconsideration of Value Assistance",
    description: "Expert-guided ROV submission if appraisal comes in below purchase price — comp selection and formal dispute filing.",
    tokens: 300,
    pct: "~2%",
    deliveryTime: "2–4 business days",
    badge: "Strategic",
    badgeColor: "bg-violet-500/20 text-violet-300 border-violet-500/30",
    certifications: ["Licensed Appraiser Review"],
    experience: "10+ yrs avg",
    rating: 4.6,
    reviews: 51,
    aiTip: "An ROV can recover a deal when an appraisal comes in low. Success rates improve significantly with properly documented comparable sales.",
  },
  {
    id: "appraisal_ai",
    category: "appraisal",
    phases: ["pre_offer", "appraisal"],
    name: "AI Appraisal Risk Analysis",
    description: "AI-powered pre-appraisal comp scan to flag appraisal gap risk before you're locked into a contract.",
    tokens: 25,
    pct: "minimal",
    deliveryTime: "Instant",
    badge: "AI-Powered",
    badgeColor: "bg-emerald-500/20 text-emerald-300 border-emerald-500/30",
    certifications: ["Automated AVM + AI Layer"],
    experience: "Real-time data",
    rating: 4.5,
    reviews: 208,
    aiTip: "AI analysis catches ~80% of appraisal gap risk before contract. Highly recommended before submitting offers above list price.",
  },

  // ── INSPECTION ──
  {
    id: "inspection_pool",
    category: "inspection",
    phases: ["inspection"],
    name: "Pool & Spa Inspection",
    description: "Comprehensive inspection of pool/spa equipment, structural shell, plumbing, electrical, and safety compliance.",
    tokens: 250,
    pct: "~2%",
    deliveryTime: "2–3 business days",
    badge: null,
    badgeColor: null,
    certifications: ["Certified Pool Inspector", "CA Contractor Licensed"],
    experience: "8+ yrs avg",
    rating: 4.7,
    reviews: 89,
    aiTip: "Pools can involve hidden equipment and resurfacing costs not visible during initial walkthroughs. A pool inspection typically costs $150–$400 out of pocket — tokens cover coordination and vetting.",
  },
  {
    id: "inspection_foundation",
    category: "inspection",
    phases: ["inspection"],
    name: "Foundation Inspection",
    description: "Licensed structural engineer review of foundation condition, settlement, drainage, and seismic risk factors.",
    tokens: 350,
    pct: "~2.5%",
    deliveryTime: "3–5 business days",
    badge: "High Value",
    badgeColor: "bg-red-500/20 text-red-300 border-red-500/30",
    certifications: ["Licensed Structural Engineer", "CA PE Licensed"],
    experience: "12+ yrs avg",
    rating: 4.9,
    reviews: 61,
    aiTip: "Foundation movement may require structural review by a licensed engineer. A deferred foundation issue can cost $10,000–$80,000+ to remediate — this is one of the highest-ROI inspections available.",
  },
  {
    id: "inspection_roof",
    category: "inspection",
    phases: ["inspection"],
    name: "Roof Inspection",
    description: "Detailed assessment of roof condition, remaining life, flashing, gutters, and ventilation.",
    tokens: 250,
    pct: "~2%",
    deliveryTime: "2–3 business days",
    badge: null,
    badgeColor: null,
    certifications: ["Certified Roofing Inspector", "HAAG Certified"],
    experience: "10+ yrs avg",
    rating: 4.8,
    reviews: 113,
    aiTip: null,
  },
  {
    id: "inspection_chimney",
    category: "inspection",
    phases: ["inspection"],
    name: "Chimney Inspection",
    description: "Level II chimney inspection including interior camera scan for older masonry and fireplace systems.",
    tokens: 200,
    pct: "~1.5%",
    deliveryTime: "2–3 business days",
    badge: null,
    badgeColor: null,
    certifications: ["CSIA Certified", "NFI Certified"],
    experience: "8+ yrs avg",
    rating: 4.6,
    reviews: 44,
    aiTip: "Older chimneys may require additional inspection for seismic and safety compliance. Camera inspection can reveal interior flue damage invisible from outside.",
  },
  {
    id: "inspection_sewer",
    category: "inspection",
    phases: ["inspection"],
    name: "Sewer Scope",
    description: "Video camera inspection of main sewer line from home to street connection to detect cracks, root intrusion, and blockages.",
    tokens: 250,
    pct: "~2%",
    deliveryTime: "1–2 business days",
    badge: "Recommended",
    badgeColor: "bg-emerald-500/20 text-emerald-300 border-emerald-500/30",
    certifications: ["Licensed Plumbing Contractor"],
    experience: "7+ yrs avg",
    rating: 4.7,
    reviews: 97,
    aiTip: "Sewer line replacement in CA averages $5,000–$15,000. A $300–$500 scope inspection is one of the best pre-closing investments you can make.",
  },
  {
    id: "inspection_hvac",
    category: "inspection",
    phases: ["inspection"],
    name: "HVAC Inspection",
    description: "Full mechanical inspection of heating, ventilation, and air conditioning systems including ductwork and efficiency rating.",
    tokens: 200,
    pct: "~1.5%",
    deliveryTime: "2–3 business days",
    badge: null,
    badgeColor: null,
    certifications: ["HVAC Licensed Contractor", "NATE Certified"],
    experience: "10+ yrs avg",
    rating: 4.7,
    reviews: 76,
    aiTip: null,
  },
  {
    id: "inspection_electrical",
    category: "inspection",
    phases: ["inspection"],
    name: "Electrical Inspection",
    description: "Panel, wiring, grounding, and safety inspection by a licensed CA electrician.",
    tokens: 200,
    pct: "~1.5%",
    deliveryTime: "2–3 business days",
    badge: null,
    badgeColor: null,
    certifications: ["CA Licensed Electrician", "C-10 Contractor"],
    experience: "10+ yrs avg",
    rating: 4.8,
    reviews: 58,
    aiTip: null,
  },
  {
    id: "inspection_plumbing",
    category: "inspection",
    phases: ["inspection"],
    name: "Plumbing Inspection",
    description: "Supply, drain, waste, vent, water heater, and fixture inspection by a licensed CA plumber.",
    tokens: 200,
    pct: "~1.5%",
    deliveryTime: "2–3 business days",
    badge: null,
    badgeColor: null,
    certifications: ["CA Licensed Plumber", "C-36 Contractor"],
    experience: "9+ yrs avg",
    rating: 4.7,
    reviews: 64,
    aiTip: null,
  },
  {
    id: "inspection_mold",
    category: "inspection",
    phases: ["inspection"],
    name: "Mold Inspection",
    description: "Air sampling and visual mold assessment with certified industrial hygienist lab analysis.",
    tokens: 300,
    pct: "~2%",
    deliveryTime: "3–5 business days",
    badge: null,
    badgeColor: null,
    certifications: ["Certified Mold Inspector", "ACAC Certified"],
    experience: "10+ yrs avg",
    rating: 4.6,
    reviews: 41,
    aiTip: null,
  },
  {
    id: "inspection_pest",
    category: "inspection",
    phases: ["inspection"],
    name: "Pest Inspection",
    description: "Wood-destroying organism (WDO) inspection including termite, dry rot, and moisture assessment. CA-required for most transactions.",
    tokens: 200,
    pct: "~1.5%",
    deliveryTime: "1–2 business days",
    badge: "CA Required",
    badgeColor: "bg-red-500/20 text-red-300 border-red-500/30",
    certifications: ["CA Licensed Pest Control", "CPCO Certified"],
    experience: "8+ yrs avg",
    rating: 4.7,
    reviews: 145,
    aiTip: null,
  },
  {
    id: "inspection_geo",
    category: "inspection",
    phases: ["inspection"],
    name: "Geological / Soil Review",
    description: "Licensed geotechnical engineer assessment for hillside, canyon, or liquefaction-zone properties.",
    tokens: 500,
    pct: "~3.5%",
    deliveryTime: "5–10 business days",
    badge: "Specialized",
    badgeColor: "bg-violet-500/20 text-violet-300 border-violet-500/30",
    certifications: ["Licensed Geotechnical Engineer", "CA PE Licensed"],
    experience: "15+ yrs avg",
    rating: 4.9,
    reviews: 19,
    aiTip: "Hillside and canyon properties in CA are subject to landslide and liquefaction risk. A geotech review is often required by lenders and is essential due diligence.",
  },

  // ── MOVING ──
  {
    id: "moving_standard",
    category: "moving",
    phases: ["closing", "post_close"],
    name: "Moving Service Coordination",
    description: "Vetted local mover matching and booking coordination — 3 competing quotes, licensed and insured carriers only.",
    tokens: 300,
    pct: "~2%",
    deliveryTime: "3–5 business days",
    badge: null,
    badgeColor: null,
    certifications: ["CA Licensed Mover", "AMSA Member"],
    experience: "8+ yrs avg",
    rating: 4.6,
    reviews: 87,
    aiTip: null,
  },
  {
    id: "moving_premium",
    category: "moving",
    phases: ["closing", "post_close"],
    name: "Premium Movers",
    description: "Full-service premium relocation with dedicated move coordinator, guaranteed delivery windows, and real-time tracking.",
    tokens: 500,
    pct: "~3.5%",
    deliveryTime: "Schedule anytime",
    badge: "Premium",
    badgeColor: "bg-amber-500/20 text-amber-300 border-amber-500/30",
    certifications: ["CA Licensed Mover", "AMSA ProMover"],
    experience: "12+ yrs avg",
    rating: 4.8,
    reviews: 52,
    aiTip: null,
  },
  {
    id: "moving_packing",
    category: "moving",
    phases: ["closing", "post_close"],
    name: "Packing Assistance",
    description: "Professional packing crew with materials — partial or full-home packing with fragile item specialization.",
    tokens: 250,
    pct: "~2%",
    deliveryTime: "Schedule anytime",
    badge: null,
    badgeColor: null,
    certifications: ["Insured & Bonded"],
    experience: "6+ yrs avg",
    rating: 4.5,
    reviews: 63,
    aiTip: null,
  },
  {
    id: "moving_white_glove",
    category: "moving",
    phases: ["closing", "post_close"],
    name: "White Glove Moving Services",
    description: "Art, antique, and high-value item transport with custom crating, climate-controlled vehicles, and white-glove handling.",
    tokens: 800,
    pct: "~6%",
    deliveryTime: "Schedule anytime",
    badge: "Luxury",
    badgeColor: "bg-amber-500/20 text-amber-300 border-amber-500/30",
    certifications: ["Fine Art Transport Certified", "Fully Insured"],
    experience: "15+ yrs avg",
    rating: 4.9,
    reviews: 28,
    aiTip: null,
  },
  {
    id: "moving_storage",
    category: "moving",
    phases: ["closing", "post_close"],
    name: "Storage Coordination",
    description: "Short or long-term storage unit sourcing, pricing comparison, and logistics coordination.",
    tokens: 200,
    pct: "~1.5%",
    deliveryTime: "2–3 business days",
    badge: null,
    badgeColor: null,
    certifications: ["Licensed Storage Partner Network"],
    experience: "7+ yrs avg",
    rating: 4.5,
    reviews: 44,
    aiTip: null,
  },

  // ── CLEANING ──
  {
    id: "cleaning_move_in",
    category: "cleaning",
    phases: ["post_close"],
    name: "Move-In Cleaning",
    description: "Deep clean of your new home before move-in — all surfaces, appliances, cabinets, bathrooms, and floors.",
    tokens: 200,
    pct: "~1.5%",
    deliveryTime: "1–2 business days",
    badge: "Popular",
    badgeColor: "bg-emerald-500/20 text-emerald-300 border-emerald-500/30",
    certifications: ["Insured & Bonded", "Background Checked"],
    experience: "6+ yrs avg",
    rating: 4.7,
    reviews: 118,
    aiTip: null,
  },
  {
    id: "cleaning_move_out",
    category: "cleaning",
    phases: ["closing", "post_close"],
    name: "Move-Out Cleaning",
    description: "Thorough move-out clean of your current home — ensures security deposit return and smooth handoff.",
    tokens: 200,
    pct: "~1.5%",
    deliveryTime: "1–2 business days",
    badge: null,
    badgeColor: null,
    certifications: ["Insured & Bonded", "Background Checked"],
    experience: "6+ yrs avg",
    rating: 4.6,
    reviews: 94,
    aiTip: null,
  },
  {
    id: "cleaning_deep",
    category: "cleaning",
    phases: ["post_close"],
    name: "Deep Cleaning Service",
    description: "Comprehensive deep clean including windows, grout, baseboards, vents, and inside all appliances.",
    tokens: 350,
    pct: "~2.5%",
    deliveryTime: "2–3 business days",
    badge: null,
    badgeColor: null,
    certifications: ["Insured & Bonded", "Background Checked"],
    experience: "8+ yrs avg",
    rating: 4.8,
    reviews: 72,
    aiTip: null,
  },
  {
    id: "cleaning_luxury",
    category: "cleaning",
    phases: ["post_close"],
    name: "Luxury Cleaning Coordination",
    description: "White-glove cleaning for high-end properties — specialized materials, discreet team, priority scheduling.",
    tokens: 500,
    pct: "~3.5%",
    deliveryTime: "Schedule anytime",
    badge: "Luxury",
    badgeColor: "bg-amber-500/20 text-amber-300 border-amber-500/30",
    certifications: ["Luxury Home Certified", "Fully Insured"],
    experience: "10+ yrs avg",
    rating: 4.9,
    reviews: 31,
    aiTip: null,
  },

  // ── MORTGAGE INSURANCE (placeholder for future module) ──
  {
    id: "mi_optimization",
    category: "mortgage",
    phases: ["mortgage", "pre_offer"],
    name: "Mortgage Insurance Optimization™",
    description: "Coming soon — scenario analysis to reduce or eliminate monthly MI through down payment structuring, lender-paid MI, or FHA vs conventional comparisons.",
    tokens: null,
    pct: null,
    deliveryTime: "Coming Soon",
    badge: "Coming Soon",
    badgeColor: "bg-slate-600/40 text-slate-400 border-slate-500/30",
    certifications: ["Bennett Liss · NMLS #1524446"],
    experience: "30+ yrs",
    rating: null,
    reviews: null,
    comingSoon: true,
    aiTip: "Choosing a slightly larger down payment may substantially reduce monthly mortgage insurance costs. In some cases, a 5% increase in down payment can eliminate MI entirely.",
  },
];

export const PHASE_SMART_SUGGESTIONS = {
  pre_offer: ["appraisal_ai", "mi_optimization"],
  inspection: ["inspection_sewer", "inspection_foundation", "inspection_pool", "inspection_pest", "inspection_chimney"],
  appraisal: ["appraisal_standard", "appraisal_rov", "appraisal_rush"],
  mortgage: ["mi_optimization"],
  closing: ["moving_standard", "cleaning_move_out"],
  post_close: ["cleaning_move_in", "moving_premium", "moving_packing", "cleaning_deep"],
};