/**
 * SmartBuy™ Marketplace Data
 * Services organized by transaction phase with token costs, descriptions, and AI guidance.
 */

// ── Transaction Timeline Stages ──
export const TRANSACTION_PHASES = [
  { id: "pre_offer", step: 1, icon: "🔍", label: "Property Intelligence", color: "emerald", when: "Before you make an offer", description: "Market analysis, property details, comparable sales, and neighborhood insights inform your offer price and strategy.", isClosing: false },
  { id: "inspection", step: 2, icon: "🔬", label: "Inspection & Due Diligence", color: "blue", when: "After offer acceptance, during contingency period", description: "Professional inspections (home, roof, foundation, pool) and appraisal coordination to uncover any issues before closing.", isClosing: false },
  { id: "appraisal", step: 3, icon: "📊", label: "Appraisal Coordination", color: "purple", when: "After inspection contingency clears", description: "Appraisal management, value disputes, and reconsideration requests to ensure fair property valuation.", isClosing: false },
  { id: "mortgage", step: 4, icon: "🏦", label: "Mortgage Guidance", color: "amber", when: "Throughout the transaction", description: "Loan program guidance, rate optimization, document preparation, and closing cost review.", isClosing: false },
  { id: "closing", step: 5, icon: "🔑", label: "Closing Preparation", color: "rose", when: "10 days before closing", description: "Final walkthrough coordination, title issues, document signing, and settlement logistics.", isClosing: true },
  { id: "post_close", step: 6, icon: "📦", label: "Post-Close Distribution", color: "slate", when: "At closing and after", description: "Token credit application, final savings distribution, and moving/cleanup service coordination.", isClosing: false },
];

// ── Service Categories ──
export const CATEGORIES = [
  { id: "intelligence", icon: "🔍", label: "Property Intelligence" },
  { id: "inspection", icon: "🔬", label: "Inspections & Due Diligence" },
  { id: "appraisal", icon: "📊", label: "Appraisal Services" },
  { id: "valuation", icon: "💰", label: "Property Valuation" },
  { id: "mortgage", icon: "🏦", label: "Mortgage & Finance" },
  { id: "offer", icon: "✍️", label: "Offer Strategy" },
  { id: "closing", icon: "🔑", label: "Closing Coordination" },
  { id: "moving", icon: "📦", label: "Moving Services" },
  { id: "cleaning", icon: "🧹", label: "Cleaning Services" },
];

// ── Closing Cost Items (for ClosingCostVisualizer) ──
export const CLOSING_COST_ITEMS = [
  // Token-eligible closing costs (buyer commission rebate can offset these)
  { id: "title_insurance", label: "Title Insurance", note: "Lender's title policy", typical: [500, 1200], token_eligible: true },
  { id: "title_search", label: "Title Search & Abstract", note: "Property ownership verification", typical: [200, 400], token_eligible: true },
  { id: "appraisal_fee", label: "Appraisal Fee", note: "Property valuation", typical: [400, 700], token_eligible: true },
  { id: "home_inspection", label: "Home Inspection", note: "General inspection fee", typical: [300, 500], token_eligible: true },
  { id: "pest_inspection", label: "Pest Inspection", note: "Termite & pest report", typical: [100, 200], token_eligible: true },
  { id: "survey", label: "Survey", note: "Property boundary survey", typical: [300, 600], token_eligible: true },
  { id: "inspection_repairs", label: "Inspection Repair Credits", note: "Negotiated repair allowances", typical: [0, 5000], token_eligible: true },
  { id: "hoa_transfer", label: "HOA Fees & Transfer", note: "HOA inspection and documents", typical: [100, 500], token_eligible: true },
  { id: "homeowners_insurance", label: "Homeowners Insurance (1yr)", note: "First year premium", typical: [800, 2000], token_eligible: true },
  { id: "recording_fees", label: "Recording Fees", note: "County deed recording", typical: [100, 300], token_eligible: true },

  // Non-eligible (lender fees)
  { id: "origination_fee", label: "Loan Origination Fee", note: "Lender fee (1-2% of loan)", typical: [3000, 10000], token_eligible: false },
  { id: "processing_fee", label: "Loan Processing Fee", note: "Lender processing & coordination", typical: [800, 1500], token_eligible: false },
  { id: "underwriting_fee", label: "Underwriting Fee", note: "Loan underwriting review", typical: [600, 1200], token_eligible: false },
  { id: "appraisal_admin_fee", label: "Appraisal Administration Fee", note: "Lender's appraisal coordination", typical: [300, 500], token_eligible: false },
  { id: "credit_report_fee", label: "Credit Report Fee", note: "Lender credit pull", typical: [75, 150], token_eligible: false },
];

// ── AI-Powered Service Suggestions by Phase ──
export const PHASE_SMART_SUGGESTIONS = {
  all: [],
  pre_offer: ["comps_sale", "market_analysis", "property_details"],
  inspection: ["general_inspection", "foundation_inspection", "appraisal_standard"],
  appraisal: ["appraisal_standard", "appraisal_rov", "comps_appraisal"],
  mortgage: ["mortgage_guidance", "rate_shop", "loan_comparison"],
  closing: ["title_insurance", "final_walkthrough", "closing_coordination"],
  post_close: ["moving_standard", "cleaning_move_in", "final_distribution"],
};

// ── All Services ──
export const SERVICES = [
  // ── PROPERTY INTELLIGENCE ──
  {
    id: "market_analysis",
    name: "Market Analysis & Comparable Sales",
    category: "intelligence",
    description: "Detailed market report showing recent sales, days on market, price trends, and competitive positioning for your target property.",
    phases: ["pre_offer"],
    tokens: 350,
    pct: "3.5%",
    rating: 4.8,
    reviews: 247,
    experience: "Real estate professionals",
    deliveryTime: "24 hours",
    why_now: "Before making your offer — know what similar homes sold for recently so you can price competitively and avoid overpaying.",
    aiTip: "This service sharpens your offer price and protects you from overpaying. Especially valuable in hot markets where comps shift daily.",
    certifications: ["MLS Data", "Real Estate Board Verified"],
    comingSoon: false,
  },
  {
    id: "property_details",
    name: "Property Details & Records Search",
    category: "intelligence",
    description: "Comprehensive property data including lot size, year built, square footage, property tax history, zoning, and utility information.",
    phases: ["pre_offer"],
    tokens: 200,
    pct: "2%",
    rating: 4.9,
    reviews: 512,
    experience: "County records specialists",
    deliveryTime: "12 hours",
    why_now: "Verify property facts before submitting your offer. Identify red flags like zoning violations, unpermitted additions, or tax liens.",
    aiTip: "Combine this with an inspection to catch misrepresented features (e.g., claimed square footage vs. county records).",
    certifications: ["County Records Access", "MLS Verified"],
    comingSoon: false,
  },
  {
    id: "comps_sale",
    name: "Comp Analysis: Recent Sales",
    category: "intelligence",
    description: "In-depth analysis of recent comparable sales in the neighborhood, filtered by size, age, and condition.",
    phases: ["pre_offer"],
    tokens: 400,
    pct: "4%",
    rating: 4.7,
    reviews: 189,
    experience: "Appraisers",
    deliveryTime: "2 days",
    why_now: "Use real comparable sales data to justify your offer price to your lender and protect against appraisal gaps.",
    aiTip: "Focus on sales from the last 60-90 days in the same ZIP or neighborhood. Older sales may not reflect current market conditions.",
    certifications: ["Certified Appraiser Review", "MLS Data"],
    comingSoon: false,
  },

  // ── INSPECTIONS & DUE DILIGENCE ──
  {
    id: "general_inspection",
    name: "General Home Inspection",
    category: "inspection",
    description: "Comprehensive professional home inspection covering structure, systems, roof, foundation, HVAC, plumbing, and electrical.",
    phases: ["inspection"],
    tokens: 450,
    pct: "4.5%",
    rating: 4.9,
    reviews: 823,
    experience: "Licensed inspectors",
    deliveryTime: "3-5 days",
    why_now: "After offer acceptance during the inspection contingency period. Identifies major issues before you're locked in financially.",
    aiTip: "Request a virtual walkthrough if the inspector is certified for it. Combine findings with contractor quotes to negotiate repairs.",
    certifications: ["ASHI Member", "Licensed Inspector", "Insured"],
    comingSoon: false,
  },
  {
    id: "foundation_inspection",
    name: "Foundation & Structural Inspection",
    category: "inspection",
    description: "Specialized inspection of foundation, basement, structural walls, crawl space, and any visible cracks or settling issues.",
    phases: ["inspection"],
    tokens: 350,
    pct: "3.5%",
    rating: 4.6,
    reviews: 342,
    experience: "Structural engineers",
    deliveryTime: "2-3 days",
    why_now: "Essential in older homes or if general inspection flags foundation concerns. Foundation repairs are expensive — catch them early.",
    aiTip: "If the report shows minor settling or hairline cracks, get a second opinion from a structural engineer. Not all cracks require repair.",
    certifications: ["Structural Engineer", "PE Licensed"],
    comingSoon: false,
  },
  {
    id: "roof_inspection",
    name: "Roof Inspection & Report",
    category: "inspection",
    description: "Professional roof inspection including shingles, flashing, gutters, ventilation, and remaining roof life assessment.",
    phases: ["inspection"],
    tokens: 250,
    pct: "2.5%",
    rating: 4.8,
    reviews: 478,
    experience: "Roofing contractors",
    deliveryTime: "1-2 days",
    why_now: "Roof replacement is expensive. Get a professional assessment before closing so you can negotiate repairs or credits.",
    aiTip: "If the roof is over 15 years old, budget for replacement within 5-10 years. Use inspection findings to negotiate credits.",
    certifications: ["Roofing Contractor License", "Insured"],
    comingSoon: false,
  },
  {
    id: "pool_spa_inspection",
    name: "Pool & Spa Inspection",
    category: "inspection",
    description: "Inspection of pool structure, pump/filter systems, heater, plumbing, chemical balance, and safety features.",
    phases: ["inspection"],
    tokens: 200,
    pct: "2%",
    rating: 4.7,
    reviews: 156,
    experience: "Pool technicians",
    deliveryTime: "1-2 days",
    why_now: "Pool repairs and equipment replacement are costly. Identify needed repairs before closing.",
    aiTip: "Request a 10-year equipment maintenance history. Aging pumps and heaters often need replacement soon after purchase.",
    certifications: ["Certified Pool Inspector", "Licensed"],
    comingSoon: false,
  },
  {
    id: "sewer_scope",
    name: "Sewer Scope / Plumbing Line Inspection",
    category: "inspection",
    description: "Video camera inspection of sewer line and underground plumbing to detect cracks, clogs, roots, or misalignment.",
    phases: ["inspection"],
    tokens: 220,
    pct: "2.2%",
    rating: 4.5,
    reviews: 289,
    experience: "Licensed plumbers",
    deliveryTime: "1 day",
    why_now: "Sewer line repairs can cost $3K–$25K. A $200 inspection now can save thousands later.",
    aiTip: "If roots are detected, ask what plants/trees are causing it. Get a quote for root removal before you close.",
    certifications: ["Licensed Plumber", "Camera Equipment Certified"],
    comingSoon: false,
  },
  {
    id: "pest_inspection",
    name: "Pest & Termite Inspection",
    category: "inspection",
    description: "Professional pest and termite inspection covering interior, exterior, foundation, and attic for signs of infestation or damage.",
    phases: ["inspection"],
    tokens: 150,
    pct: "1.5%",
    rating: 4.9,
    reviews: 612,
    experience: "Pest control specialists",
    deliveryTime: "1-2 days",
    why_now: "Many lenders require this before closing. Termite damage is expensive to repair. Catch it early.",
    aiTip: "If termites are found, get a treatment quote and a warranty. Many pest companies offer 1-year re-inspection warranties.",
    certifications: ["Certified Pest Inspector", "Licensed"],
    comingSoon: false,
  },
  {
    id: "mold_inspection",
    name: "Mold Inspection & Air Quality Test",
    category: "inspection",
    description: "Air quality test and visual inspection for mold, moisture, and indoor air quality issues.",
    phases: ["inspection"],
    tokens: 280,
    pct: "2.8%",
    rating: 4.6,
    reviews: 201,
    experience: "Environmental inspectors",
    deliveryTime: "3-5 days",
    why_now: "Mold can cause health issues. Get tested if you see water stains, smell odors, or have concerns.",
    aiTip: "Mold is common in basements after heavy rain. Treatment is usually $500–$2K. Get a quote before closing.",
    certifications: ["Certified Mold Inspector", "EPA-Licensed"],
    comingSoon: false,
  },
  {
    id: "hvac_inspection",
    name: "HVAC System Inspection & Report",
    category: "inspection",
    description: "Comprehensive HVAC inspection including furnace, air conditioning, ductwork, refrigerant levels, and efficiency rating.",
    phases: ["inspection"],
    tokens: 200,
    pct: "2%",
    rating: 4.8,
    reviews: 334,
    experience: "Licensed HVAC technicians",
    deliveryTime: "1-2 days",
    why_now: "HVAC replacement is $5K–$12K. Know the age and condition before you close.",
    aiTip: "Ask about maintenance history. Systems serviced regularly last longer. Get a replacement estimate if it's over 15 years old.",
    certifications: ["EPA Section 608 Certified", "Licensed HVAC Technician"],
    comingSoon: false,
  },

  // ── APPRAISAL SERVICES ──
  {
    id: "appraisal_standard",
    name: "Standard Appraisal Coordination",
    category: "appraisal",
    description: "Coordination of property appraisal ordered by your lender, including scheduling, inspector communication, and value verification.",
    phases: ["appraisal"],
    tokens: 300,
    pct: "3%",
    rating: 4.7,
    reviews: 412,
    experience: "Appraisal coordinators",
    deliveryTime: "5-7 days",
    why_now: "After inspection contingency closes. Your lender requires this. SmartBuy can coordinate and monitor the process.",
    aiTip: "If the appraisal comes in low, we can challenge it with comps. Appraisal gaps can cost you thousands at closing.",
    certifications: ["Appraisal Management Company Certified"],
    comingSoon: false,
  },
  {
    id: "appraisal_rush",
    name: "Rush Appraisal Coordination",
    category: "appraisal",
    description: "Expedited appraisal scheduling and coordination when standard timelines won't work.",
    phases: ["appraisal"],
    tokens: 450,
    pct: "4.5%",
    rating: 4.5,
    reviews: 98,
    experience: "Appraisal management",
    deliveryTime: "2-3 days",
    why_now: "Close timing issues or contingency extension. Costs more but gets your appraisal back in time.",
    aiTip: "Rush appraisals may cost extra with the appraiser, but we can often negotiate within the AMC.",
    certifications: ["Expedited Appraisal Coordination"],
    comingSoon: false,
  },
  {
    id: "appraisal_rov",
    name: "Reconsideration of Value (ROV)",
    category: "appraisal",
    description: "Challenge low appraisals by submitting additional comparable sales data and rebuttal arguments to the appraiser.",
    phases: ["appraisal"],
    tokens: 200,
    pct: "2%",
    rating: 4.3,
    reviews: 167,
    experience: "Real estate professionals",
    deliveryTime: "3-5 days",
    why_now: "If your appraisal comes in lower than your offer price. A successful ROV can save you thousands.",
    aiTip: "Success rate is ~40%. Strongest ROVs use recent comps of similar homes with similar features.",
    certifications: ["Appraisal Appeal Specialist"],
    comingSoon: false,
  },

  // ── HOUSECANARY PROPERTY VALUATION (Coming Soon) ──
  {
    id: "hc_property_value",
    name: "HouseCanary Property Valuation",
    category: "valuation",
    description: "Independent AI-powered property valuation from HouseCanary. Compare to appraisal. Includes value forecast and market analysis.",
    phases: ["pre_offer", "appraisal"],
    tokens: null,
    pct: null,
    why_now: "Get an independent valuation before making an offer or if your appraisal seems low.",
    comingSoon: true,
    badge: "Coming Soon",
    badgeColor: "border-slate-600 bg-slate-700/40 text-slate-400",
  },
  {
    id: "hc_market_report",
    name: "HouseCanary Market Intelligence Report",
    category: "valuation",
    description: "Property-level market analysis from HouseCanary, including neighborhood trends, comparable sales, and investment metrics.",
    phases: ["pre_offer"],
    tokens: null,
    pct: null,
    why_now: "Before submitting your offer — understand the market, comps, and whether this is a good deal.",
    comingSoon: true,
    badge: "Coming Soon",
    badgeColor: "border-slate-600 bg-slate-700/40 text-slate-400",
  },
  {
    id: "hc_risk_assessment",
    name: "HouseCanary Property Risk Assessment",
    category: "valuation",
    description: "AI-powered risk assessment covering flood hazards, earthquake risk, wildfire risk, environmental factors, and insurance implications.",
    phases: ["inspection"],
    tokens: null,
    pct: null,
    why_now: "Understand natural hazard risks before closing. Informs insurance decisions and long-term property management.",
    comingSoon: true,
    badge: "Coming Soon",
    badgeColor: "border-slate-600 bg-slate-700/40 text-slate-400",
  },
  {
    id: "hc_investment_analysis",
    name: "HouseCanary Investment Property Analysis",
    category: "valuation",
    description: "Cash flow projections, rental potential, cap rate analysis, and investment metrics for rental or investment properties.",
    phases: ["pre_offer"],
    tokens: null,
    pct: null,
    why_now: "For investment property buyers — understand potential rental income, expenses, and return on investment.",
    comingSoon: true,
    badge: "Coming Soon",
    badgeColor: "border-slate-600 bg-slate-700/40 text-slate-400",
  },

  // ── MORTGAGE & FINANCE ──
  {
    id: "mortgage_guidance",
    name: "Mortgage Consultation with Bennett Liss",
    category: "mortgage",
    description: "Direct consultation with Bennett Liss (NMLS #1524446) on loan programs, rates, terms, and financing strategy.",
    phases: ["mortgage", "closing"],
    tokens: 800,
    pct: "8%",
    rating: 5,
    reviews: 487,
    experience: "30 years CA mortgage",
    deliveryTime: "Within 2 hours",
    why_now: "At any point during your transaction — pre-approval, rate lock, program selection, or closing prep.",
    aiTip: "Bennett specializes in VA loans, FHA streamlines, and jumbo loans. Talk to him if you have complex financing needs.",
    certifications: ["NMLS #1524446", "CA DRE #01107013", "30-Year Expert"],
    comingSoon: false,
  },
  {
    id: "rate_shop",
    name: "Rate Comparison & Shopping",
    category: "mortgage",
    description: "Shop your rate with multiple lenders to ensure you're getting the best terms available.",
    phases: ["mortgage"],
    tokens: 500,
    pct: "5%",
    rating: 4.8,
    reviews: 234,
    experience: "Mortgage brokers",
    deliveryTime: "3-5 days",
    why_now: "After pre-qualification but before rate lock. Saving 0.25% on your rate can mean $10K+ in lifetime savings.",
    aiTip: "Request quotes with same terms (program, points, closing costs) so you can compare apples-to-apples.",
    certifications: ["Licensed Mortgage Broker"],
    comingSoon: false,
  },
  {
    id: "loan_comparison",
    name: "Loan Program Comparison & Analysis",
    category: "mortgage",
    description: "Analysis of available loan programs (Conventional, FHA, VA, Jumbo) with cost-benefit comparisons.",
    phases: ["mortgage"],
    tokens: 600,
    pct: "6%",
    rating: 4.9,
    reviews: 156,
    experience: "Mortgage experts",
    deliveryTime: "2-3 days",
    why_now: "If you're comparing FHA vs. Conventional, VA vs. Conventional, or deciding between loan types.",
    aiTip: "Consider total costs over your expected holding period, not just the lowest monthly payment.",
    certifications: ["Loan Officer Certified"],
    comingSoon: false,
  },

  // ── OFFER STRATEGY ──
  {
    id: "offer_strategy",
    name: "Offer Strategy & Negotiation Review",
    category: "offer",
    description: "Expert review of your offer price, contingencies, financing terms, and negotiation approach before submission.",
    phases: ["pre_offer"],
    tokens: 1000,
    pct: "10%",
    rating: 4.9,
    reviews: 289,
    experience: "Real estate negotiators",
    deliveryTime: "4 hours",
    why_now: "Before you submit your offer. A strategic offer can win the deal, save you money, and protect your interests.",
    aiTip: "Coordinate with your lender on financing terms before submitting. Weak financing terms kill otherwise good offers.",
    certifications: ["Certified Negotiation Specialist"],
    comingSoon: false,
  },

  // ── CLOSING SERVICES ──
  {
    id: "closing_coordination",
    name: "Closing Coordination & Walkthrough",
    category: "closing",
    description: "Coordinate final walkthrough, schedule closing appointment, review closing disclosure, and manage last-minute issues.",
    phases: ["closing"],
    tokens: 550,
    pct: "5.5%",
    rating: 4.8,
    reviews: 401,
    experience: "Closing coordinators",
    deliveryTime: "Ongoing until close",
    why_now: "10 days before closing. Makes sure everything is ready and no surprises pop up on closing day.",
    aiTip: "Schedule your final walkthrough 24 hours before closing when possible. Verify repairs were completed.",
    certifications: ["Closing Coordinator Certified"],
    comingSoon: false,
  },
  {
    id: "final_walkthrough",
    name: "Final Walkthrough & Punch List",
    category: "closing",
    description: "Professional final walkthrough to verify all agreed repairs are complete, utilities work, and property condition matches contract.",
    phases: ["closing"],
    tokens: 300,
    pct: "3%",
    rating: 4.9,
    reviews: 523,
    experience: "Real estate inspectors",
    deliveryTime: "24 hours",
    why_now: "24 hours before closing. Don't close until you walk through and verify everything is ready.",
    aiTip: "Bring a flashlight, check water pressure, test lights, verify agreed repairs. This is your last chance to catch issues.",
    certifications: ["Final Walkthrough Specialist"],
    comingSoon: false,
  },
  {
    id: "title_insurance",
    name: "Title Insurance & Escrow Management",
    category: "closing",
    description: "Title company coordination, title insurance policy, and escrow account setup and management.",
    phases: ["closing"],
    tokens: 400,
    pct: "4%",
    rating: 4.7,
    reviews: 312,
    experience: "Title companies",
    deliveryTime: "Ongoing until close",
    why_now: "Your lender requires this. Title insurance protects you from ownership disputes and liens.",
    aiTip: "Title insurance is typically $500–$1,200 depending on property value. Non-negotiable but often included in closing costs.",
    certifications: ["Title Company Licensed", "CLTA Member"],
    comingSoon: false,
  },

  // ── MOVING & CLEANUP ──
  {
    id: "moving_standard",
    name: "Moving Service Coordination",
    category: "moving",
    description: "Coordination of moving companies, scheduling, and logistics for your relocation.",
    phases: ["post_close"],
    tokens: 200,
    pct: "2%",
    rating: 4.6,
    reviews: 187,
    experience: "Moving coordinators",
    deliveryTime: "1-2 weeks",
    why_now: "After closing. We coordinate with vetted movers to get you the best rates.",
    aiTip: "Book movers 2-4 weeks in advance. End-of-month moves are more expensive. Mid-week moves are cheaper.",
    certifications: ["Moving Industry Certified"],
    comingSoon: false,
  },
  {
    id: "moving_premium",
    name: "Premium Moving & Packing Service",
    category: "moving",
    description: "Full-service moving including packing, loading, transport, unloading, and unpacking at your new home.",
    phases: ["post_close"],
    tokens: 350,
    pct: "3.5%",
    rating: 4.8,
    reviews: 142,
    experience: "Full-service movers",
    deliveryTime: "1-3 weeks",
    why_now: "After closing if you want hands-off moving. Premium service includes packing and unpacking.",
    aiTip: "Full-service moves cost more but save you time and labor. Get quotes from multiple companies.",
    certifications: ["Full-Service Mover Certified", "AMSA Member"],
    comingSoon: false,
  },
  {
    id: "packing_assist",
    name: "Packing Assistance & Organization",
    category: "moving",
    description: "Professional packing services to organize belongings, label boxes, and prepare for moving day.",
    phases: ["post_close"],
    tokens: 200,
    pct: "2%",
    rating: 4.7,
    reviews: 98,
    experience: "Professional organizers",
    deliveryTime: "1-2 weeks",
    why_now: "2-3 weeks before your move. Packing early reduces moving day stress.",
    aiTip: "Color-code boxes by room. Use small boxes for heavy items. Leave fragile items for last.",
    certifications: ["Professional Organizer Certified"],
    comingSoon: false,
  },

  // ── CLEANING SERVICES ──
  {
    id: "cleaning_move_in",
    name: "Move-In Cleaning & Deep Clean",
    category: "cleaning",
    description: "Professional deep cleaning of your new home before move-in, including all surfaces, appliances, and fixtures.",
    phases: ["post_close"],
    tokens: 150,
    pct: "1.5%",
    rating: 4.9,
    reviews: 578,
    experience: "Professional cleaners",
    deliveryTime: "1-3 days",
    why_now: "Before moving into your new home. Start fresh in a clean space.",
    aiTip: "Move-in cleaning is cheaper than post-move cleaning. Schedule before furniture arrives.",
    certifications: ["Bonded & Insured", "Green Cleaning Certified"],
    comingSoon: false,
  },
  {
    id: "cleaning_move_out",
    name: "Move-Out Cleaning & Deposit Protection",
    category: "cleaning",
    description: "Professional move-out cleaning of your old home to maximize security deposit return or prepare for sale.",
    phases: ["post_close"],
    tokens: 150,
    pct: "1.5%",
    rating: 4.8,
    reviews: 421,
    experience: "Professional cleaners",
    deliveryTime: "1-2 days",
    why_now: "On your move-out day. Protects your security deposit and leaves property in good condition.",
    aiTip: "Have the landlord inspect after cleaning. Disputes over cleaning costs are common.",
    certifications: ["Bonded & Insured"],
    comingSoon: false,
  },
  {
    id: "cleaning_deep",
    name: "Deep Cleaning Service",
    category: "cleaning",
    description: "Comprehensive deep cleaning covering all rooms, baseboards, cabinets, windows, and appliances.",
    phases: ["post_close"],
    tokens: 250,
    pct: "2.5%",
    rating: 4.9,
    reviews: 312,
    experience: "Professional cleaners",
    deliveryTime: "2-4 hours",
    why_now: "After move-in or before entertaining. Refreshes your space thoroughly.",
    aiTip: "Deep cleaning costs $200–$600 depending on home size. Quarterly or yearly deep cleans extend furnishing life.",
    certifications: ["Bonded & Insured", "IICRC Certified"],
    comingSoon: false,
  },
];