import { useState } from "react";
import { HelpCircle, ChevronDown, ChevronUp, Zap, TrendingUp } from "lucide-react";
import { usePageTitle } from "@/lib/usePageTitle";

const FAQS = [
  {
    category: "SmartBuy Cash™ Service",
    questions: [
      {
        q: "What is SmartBuy Cash™?",
        a: "SmartBuy Cash™ is real buyer savings generated by unbundling the traditional commission. Instead of pre-paying commissions, your SmartBuy Savings Pool gives you actual cash that you can intelligently allocate toward professional help—appraisals, inspections, offer strategy, mortgage consultation, and more—only when you need it."
      },
      {
        q: "How much SmartBuy Cash™ do I get?",
        a: "Your SmartBuy Cash™ balance is calculated as 2.5% of your target purchase price. For example, on a $750,000 home, you'd have $18,750 available. You keep whatever cash you don't spend—it's yours to take to closing or apply toward closing costs or your down payment."
      },
      {
        q: "How much does each service cost in SmartBuy Cash™?",
        a: "Each service has a fixed cost. For example, a general home inspection might cost $450, mortgage guidance $800, or offer strategy review $1,000. You can preview the cost and see what's available before allocating any of your cash."
      },
      {
        q: "Can I use my SmartBuy Cash™ to pay for closing costs?",
        a: "Yes. At closing, any remaining cash can be applied toward closing costs like title insurance, appraisals, inspections, homeowners insurance, and HOA fees. Lender-imposed fees cannot be paid with SmartBuy Cash™."
      },
      {
        q: "What happens to SmartBuy Cash™ I don't spend?",
        a: "Unused SmartBuy Cash™ is credited to you at closing as a cash savings credit. You keep the money—whether you spend it on services or not. That's real preserved buyer wealth."
      },
      {
        q: "Are all services available immediately?",
        a: "Services become accessible based on your transaction stage. You can't order appraisal coordination before you're under contract, for example. The marketplace shows which services are available at your current stage."
      },
      {
        q: "What if I'm not satisfied with a service?",
        a: "SmartBuy guarantees your satisfaction. If you're unhappy with a professional service, you can request a replacement provider or a cash refund through the SmartBuy Savings Guarantee™. Final transactions (like completed appraisals or closed loans) cannot be reversed."
      }
    ]
  },
  {
    category: "HouseCanary Reports",
    questions: [
      {
        q: "What are HouseCanary reports?",
        a: "HouseCanary is an AI-powered real estate intelligence platform that provides independent property valuations, market analysis, risk assessments, and investment metrics. SmartBuy integrates HouseCanary reports as low-cost SmartBuy Cash™ add-ons to your property intelligence toolkit."
      },
      {
        q: "What types of HouseCanary reports are available?",
        a: "We offer four HouseCanary reports: Property Valuation (AI estimate of market value), Market Intelligence (neighborhood trends and comps), Risk Assessment (flood, earthquake, wildfire, and climate risks), and Investment Analysis (for rental and investment property evaluations)."
      },
      {
        q: "How much do HouseCanary reports cost?",
        a: "Each HouseCanary report costs only $30 in SmartBuy Cash™—much less than traditional appraisals or market analyses. You can combine them for comprehensive property intelligence before making an offer."
      },
      {
        q: "How is HouseCanary different from a traditional appraisal?",
        a: "HouseCanary uses AI and public data to estimate property value quickly and affordably. A traditional appraisal is ordered by your lender and required for loan approval. HouseCanary is a second opinion to help you decide whether to make an offer—it does not replace the lender's appraisal."
      },
      {
        q: "Can I use HouseCanary reports to dispute a low appraisal?",
        a: "Not directly, but you can use HouseCanary's comparable sales data and valuation as supporting evidence when requesting a Reconsideration of Value (ROV) from your lender if an appraisal comes in low."
      },
      {
        q: "When should I order HouseCanary reports?",
        a: "Best time is before making an offer—use Property Valuation and Market Intelligence ($60 in SmartBuy Cash™) to verify you're paying a fair price. After going under contract, use Risk Assessment ($30) to understand environmental factors. For investment properties, use Investment Analysis ($30) to model cash flow."
      },
      {
        q: "Is HouseCanary data accurate?",
        a: "HouseCanary uses public records, MLS data, and machine learning for valuations. Accuracy is generally very good for market value estimates, but AI estimates can be 3–5% off in unusual markets. Always combine with traditional market analysis and professional judgment."
      }
    ]
  }
];

function FAQItem({ q, a }) {
  const [open, setOpen] = useState(false);

  return (
    <div className="border border-slate-200 rounded-lg overflow-hidden hover:border-slate-300 transition">
      <button
        onClick={() => setOpen(!open)}
        className="w-full text-left px-5 py-3.5 flex items-start gap-3 hover:bg-slate-50 transition"
      >
        <div className="flex-1 min-w-0">
          <p className="text-sm font-semibold text-slate-900 leading-relaxed">{q}</p>
        </div>
        <div className="flex-shrink-0 text-slate-400 mt-0.5">
          {open ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
        </div>
      </button>
      {open && (
        <div className="px-5 py-4 bg-slate-50 border-t border-slate-200 text-sm text-slate-700 leading-relaxed">
          {a}
        </div>
      )}
    </div>
  );
}

function CategorySection({ category, questions }) {
  return (
    <div className="mb-10">
      <h3 className="text-lg font-black text-slate-900 mb-4 flex items-center gap-2">
        {category === "Token-Available Service" ? (
          <Zap className="h-5 w-5 text-amber-500" />
        ) : (
          <TrendingUp className="h-5 w-5 text-emerald-600" />
        )}
        {category}
      </h3>
      <div className="space-y-3">
        {questions.map((item, i) => (
          <FAQItem key={i} q={item.q} a={item.a} />
        ))}
      </div>
    </div>
  );
}

export default function TokenAvailableFAQ() {
  usePageTitle("SmartBuy Cash™ & HouseCanary Reports FAQ | BuyWiser SmartBuy™");

  return (
    <div className="bg-white py-16">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="flex items-start gap-4 mb-10">
          <div className="w-10 h-10 rounded-lg bg-blue-100 border border-blue-300 flex items-center justify-center flex-shrink-0">
            <HelpCircle className="h-5 w-5 text-blue-700" />
          </div>
          <div>
            <h1 className="text-3xl font-black text-slate-900 mb-2">Frequently Asked Questions</h1>
            <p className="text-slate-600 text-base">Learn how SmartBuy Cash™ services and HouseCanary reports work within SmartBuy.</p>
          </div>
        </div>

        {/* Quick Links */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-12 pb-8 border-b border-slate-200">
          {FAQS.map((section, i) => (
            <a
              key={i}
              href={`#${section.category.replace(/\s+/g, "-").toLowerCase()}`}
              className="p-4 rounded-xl border border-slate-200 hover:border-slate-300 hover:bg-slate-50 transition text-sm font-semibold text-slate-700"
            >
              {section.category === "SmartBuy Cash™ Service" ? (
                <Zap className="h-4 w-4 text-amber-500 inline mr-2" />
              ) : (
                <TrendingUp className="h-4 w-4 text-emerald-600 inline mr-2" />
              )}
              {section.category}
            </a>
          ))}
        </div>

        {/* FAQ Sections */}
        {FAQS.map((section, i) => (
          <div key={i} id={section.category.replace(/\s+/g, "-").toLowerCase()}>
            <CategorySection category={section.category} questions={section.questions} />
          </div>
        ))}

        {/* CTA */}
        <div className="mt-12 p-6 bg-blue-50 border border-blue-200 rounded-xl text-center">
          <p className="text-sm text-slate-700 mb-3">Still have questions?</p>
          <a href="/Contact" className="inline-block px-6 py-3 bg-blue-800 text-white font-black rounded-lg hover:bg-blue-900 transition text-sm">
            Request a Consultation
          </a>
        </div>
      </div>
    </div>
  );
}